extends: "airbnb-base"
parserOptions:
  ecmaVersion: 8
env:
  node: true
  es6: true
rules:
  consistent-this: ["error", "self"]
  indent: ["error", "tab", {SwitchCase: 1}]
  no-console: "error"
  no-tabs: "off"
  max-len: ["error", { code: 120 }]
  comma-dangle: ["error", "never"]
  padded-blocks: ["error", { classes: "always", blocks: "never" }]
  no-use-before-define: ["error", { functions: false, classes: true, variables: true }]
  no-unused-vars: ["error", { vars: "all", args: "none", ignoreRestSiblings: true }]
  arrow-body-style: ["off"]
